---
title: "Practical 4-1"
output: 
  learnr::tutorial:
    theme: lumen
    includes:
      in_header: !expr system.file("tutorials/google-font.html", package = "RPiR")
runtime: shiny_prerendered
description: >
  Students learn how to write a data package.
---

```{r setup, include=FALSE}
library(learnr)
 
knitr::opts_chunk$set(error = TRUE)
set.seed(123)
```


## Overview

*In this session you will take some classic biodiversity data and turn it into an R package.*

## Background

When we think about biodiversity data, we generally think about the hypothesis
we are testing, how we are going to collect the data, and how we need to analyse
it to investigate that hypothesis. Little thought is usually given to how to 
store the data. This is a mistake! Large amounts of hard work in the field can
be wasted by mistakes in storage. After regular backups so you don’t physically
lose your data (if you’re not doing this, then you should think about it very
hard), the next important thing to consider is whether you are always using the
most up-to-date, error-free copy of your dataset.

If your data is stored in one or more csv files or excel spreadsheets, you need
to read that file into R. For that you need to know where it is. If you only 
have one copy of it on your computer, and you update that when you clean the 
data or add new records, then that is a single point of failure. If you
accidentally make incorrect edits or delete the file, then you are entirely 
dependent on backups to recover from your mistakes.

If, on the other hand, you create a new file every time you update the data, 
then all of your R scripts that do analyses on the data now have to refer to the
new file, or you will need to copy the new data file to the projects where you
are doing the analysis. If you don’t do either of these everywhere you are 
working on the data, one or more of your analyses may be using an out of date 
version of the data, and silently give incorrect answers.

Even if your behaviour is perfect, and you never make mistakes with your data,
then it is usually necessary to do some processing to the data before carrying 
out the analyses. This may be as simple as changing some of the column names in 
your tables so they are easier to work with in R (no spaces, for instance), some
cleaning of the data to remove missing data, or some significant processing to 
turn records that are easy to collect into data that is easy to analyse. Such a
script, just like the data, needs to be updated, and the code needs to be 
present wherever you carry out an analysis. It therefore suffers from exactly 
the same problems as the data itself.

There is a simple(-ish!) solution though. You don’t need to carry around your 
own copy of `ggplot()` or `lmer()` in every script you write, so why should you 
have to do it with the data? There is one definitive version of `ggplot()` and 
`lmer()` on your computer, and you just refer to them by loading the {ggplot2} 
and {lme4} packages using the `library()` function. When these packages get 
updated to fix bugs or extend functionality, you just do it once by installing
(normally updating) the R package, and then all of your scripts use the new 
version. So why not turn your data into an R package and do the same?

## Tasks

You need to download the Barro Colorado Forest Census Plot Data from the 
Smithsonian’s repository at https://repository.si.edu/handle/10088/20925. 
Download files 3 and 4, the full census data 
(<span style="color: #1697C0;">ViewFullTable.zip</span>) and the taxonomic data 
on all of the species present 
(<span style="color: #1697C0;">ViewTax.txt</span>), and download 
<span style="color: #1697C0;">generate-data.R</span> and other files from 
Moodle. You’re now ready to start. Create a private repository on GitHub with a
suitable name, and create a project based on that git repository. Store it 
somewhere sensible on your computer.

We’ll go through the process of creating a package, processing the data, 
inserting the data into the package, and building the package so that you can 
use it during the class. Remember **under no circumstances** commit the raw BCI
records to your repository – it’s far too big. I’ll show you how to ignore it so 
that you don’t do this by mistake. Once you have a working package, you’ll need 
to add documentation to remind you what the package does – see
https://r-pkgs.org/description.html and https://r-pkgs.org/data.html for more
information, and then you’ll be checking each other’s packages to make sure they
work. You can add someone as a collaborator (so they can see your package) by 
going to <span style="color: #1697C0;">Settings > Collaborators</span> from the
repository web page.

## Running the code

The critical test is that you can restart R, call `library(mypackage)` on your
package (where `mypackage` is the name of the package you created, I’m going to 
call it <span style="color: #de77ae;">BCI</span>), and then immediately access 
the data that you created. If you are testing someone else’s you’ll need to 
download it first by creating a new project based on the GitHub repository or by 
calling `devtools::install_github("username/packagename")`.

## Additional work

Finally, if you have time, select another biodiversity dataset – you could, for
instance, take one from the BioTIME repository at 
http://biotime.st-andrews.ac.uk/ – and create a new package yourself to show you 
understood the process.

## Submission

Once the package(s) is/are working, you need to submit it/them as your 
assignment for today. First you need to make sure you have pushed all of the 
changes to GitHub, then add me, 
**richardreeve**, as a collaborator on your
repository on GitHub, and then submit the link to the GitHub web page for your
repository as your exercise on GitHub. 

If you’d like to write a short script
demonstrating it working, you can add an R file to the repository, you can put 
this in an <span style="color: #de77ae;">inst</span> directory, not the existing 
<span style="color: #de77ae;">R</span> directory (which is where
package functions are stored), or the package will very likely not build. Check 
this by clicking <span style="color: #de77ae;">Install and Restart</span> before 
you submit your package!
