---
title: "Flow control"
date: '`r format(Sys.Date(), "%B %d %Y")`'
output:
  rmarkdown::html_vignette:
  toc: true
  toc_depth: 2
  vignette: >
    %\VignetteIndexEntry{Flow control}
    %\VignetteEngine{knitr::knitr}
    %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Comparisons -- testing for equality and difference

These tests are essential for `while` loops, and other forms of flow control
such as `if` statements. They allow us to test whether something is true, and
change what lines of code are run depending on the outcome. There are the
basic tests:

- `a == b`: is `a` equal to `b`? (`TRUE` if this is true, `FALSE` if this is false)
- `a > b`: is `a` greater than `b`?
- `a < b`: is `a` less than `b`?
- `a >= b`: is `a` greater than or equal to `b`?
- `a <= b`: is `a` less than or equal to `b`?
- `a != b`: is `a` different from `b`?

There are then three basic ways of changing or combining the above:

- `(a < b) || (c == d)`: is **either ** `a` less than `b` **or** `c` equal to `d`?
- `(a < b) && (c == d)`: is **both** `a` less than `b` **and** `c` equal to `d`?
- `!((a < b) && (c == d))`: is the above **not** `TRUE`? `TRUE` if the above was
  `FALSE` and vice versa 

Remember to use lots of brackets to ensure you are combining things in the right
order. These tests are used in `while` loops above to determine whether to
continue through the loop again, and in `if` statements below, to determine what
to do next.

We introduced these concepts on Friday 29th, and again in [Lecture
7a][lecture-7a] on Monday 1st and Practical `practicalA-2`. Comparisons are also
covered [in passing][operators-R4DS] in R4DS, and by R Coder in a bit more
depth [here][operators-rcoder].

# `if (something)` and `if (something) { ... } else { ... }` statements

The `if` command allow us to carry out a test, and if the result is `TRUE` carry
out a block of R code (in curly brackets `{ ... }`). Optionally, if it is
`FALSE`, a different block of code can be run instead. This allows us to do a
variety of things. To give a very simple example:

```{R}
if (2 > 1) {
  print("Maths works!")
}
```

This prints `"Maths works!"` because the test is `TRUE`, so the code block
that follows is run. Whereas:

```{R}
if (2 >= 5) {
  print("At least 5.")
} else {
  print("Less than or equal to 5.")
}
```

This prints `"Less than or equal to 5."` because the test was false, so R
continues to the code block after the `else` statement. If there is no `else`
statement, then no code is run, so:

```{R}
if (2 >= 5) {
  print("At least 5.")
}
```

does nothing. We use 'if` and `if ... else` statements throughout the helper
functions provided to you, and also in a couple of ways in the example code we
provide you. For instance:

```{R}
library(codetools)
library(RPiR)

if (length(findGlobals(plot_simple, merge=FALSE)$variables) != 0)
{
  stop("Function plot_simple() may not use global variable(s): ",
       findGlobals(plot_simple, merge=FALSE)$variables)
}
```

This checks whether `length(findGlobals(plot_simple, merge=FALSE)$variables)` is
non-zero, which is to say whether the `variables` element of what is returned by
`findGlobals(plot_simple, merge=FALSE)` is not of length zero, *i.e.* whether
there are any global variables in the function `plot_simple`. If there are, then
the contents of the curly brackets are run, `stop(...)` is called, and the code
stops running. In fact, `plot_simple` has no global variables, so the code block
is not run.

The second example we provide of using an `if` statement to control code
execution is in Practical `practical3-4`:

```{R, eval = FALSE}
if (first.graph) {
  plot_populations(final.populations,
                   new.graph = TRUE, 
                   col = c(susceptibles = "green", infecteds = "red"))
  first.graph <- FALSE 
} else {
  plot_populations(final.populations,
                   new.graph = FALSE,
                   col = c(susceptibles = "green", infecteds = "red"))
}
```

This code tests whether the variable `first.graph` is `TRUE`. If it is, the
following code block is run, and it plots a graph into a new graphics window and
sets `first.graph` to `FALSE`. This code is run inside a loop (see above), and
the next (and every subsequent) time it runs, `first.graph` is already `FALSE`
so the code block following the `else` statement is run, and a plot is
superimposed on the existing graphics window.

R Coder covers the basics of `if` statements [here][if-rcoder]. R4DS seems to
consider them too simple, but ironically they have [a chapter in Advanced
R][if-advanced-r2]; however, this contains a lot of advanced topics in flow
control that are well beyond the scope of this course.

[lecture-7a]: https://ibahcm.github.io/RPiR/lectures_html/RPiR7a-R.html

[operators-R4DS]: https://r4ds.had.co.nz/transform.html?q=compa#comparisons
[if-advanced-r2]: https://adv-r.hadley.nz/control-flow.html
[operators-rcoder]: https://r-coder.com/operators-r
[if-rcoder]: https://r-coder.com/if-else-r
