---
title: "Reference - General"
date: '`r format(Sys.Date(), "%B %d %Y")`'
output:
  rmarkdown::html_vignette:
  toc: true
  toc_depth: 2
  vignette: >
    %\VignetteIndexEntry{Reference - General}
    %\VignetteEngine{knitr::knitr}
    %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

*Various reference materials*

## British Ecological Society

The [British Ecological Society (BES)][BES] is the oldest ecological society in
the world, and one of the largest. It publishes [several excellent
journals][BES-journals], including [Methods in Ecology and Evolution][BES-MEE],
which publishes many software packages.

The society also provides many several [guides on better science][BES-guides].
As part of the course, **we require you to read the following guides**:

- [Reproducible Code][BES-repro]
- [Data Management][BES-data]

## Hadley Wickham

[Hadley Wickham][hadley-wickham] is the Chief Scientist at RStudio / Posit PBC.
He created the original `ggplot` library for his PhD. These days his
[data analysis packages][tidyverse-packages] are collectively known as the
[tidyverse][tidyverse], the most famous of which are probably [ggplot2][ggplot2]
and [dplyr][dplyr]. He has written three very useful books on data analysis and
software development in R:

- [R for Data Science (R4DS)][R4DS]
  * [Solutions to the exercises][R4DS-solutions]
- Advanced R
  - [1st edition][advanced-r] (I find this easier to navigate)
    * [Solutions to the exercises][advanced-r-solutions]
  - [2nd edition][advanced-r2] (this is obviously updated)
    * [Solutions to the exercises][advanced-r2-solutions]
- [R Packages][r-packages] (with Jenny Bryan, see more of her work below)

We recommend all of these books as reference material, and will point to
specific chapters at different times, but the books themselves are probably too
long for you to read in their entirety. Nonetheless keep them for future
reference, as they contain an enormous amount of knowledge about R in a
(relatively!) compact form. BOHVM also interviewed Hadley as part of our Naturally
Speaking podcast when he came to Glasgow to receive an award from the university
a few years ago. You can hear the interview [here][naturally-speaking].

## Jenny Bryan

[Jenny Bryan][jenny-bryan] is a statistician who also works for RStudio / Posit
PBC. She has also produced an enormous amount of fantastic material, which
actually aligns even more closely with the course than Hadley's work, since she
is interested in reproducibility and better coding practice.

#### Understanding, avoiding and fixing errors in your code

As part of the course, **we require you to watch [this
keynote][rstudioconf2020-jb]** from rstudio::conf 2020 by Jenny. It is an
excellent keynote on errors in R and how to identify and fix them.

#### Better coding practices

Jenny (and Jim Hester) have written a guide called "*What they forgot to tell you
about R*" which is available online [here][what-they-forgot]. She also gave a
talk a few years ago (in 2015) at a Reproducible Science Workshop and as part of
the course **we require you to flick through [the slides][name-files]** to give
you an idea about how to better name your files in the future.

#### Git and GitHub in R and RStudio

Git is a very complex tool -- it is used to manage the development of the whole
Linux kernel! -- so we cover only the most basic aspects of it in this course.
As well as all of the above, Jenny (with others) has written an excellent
resource for using git and GitHub in R -- [Happy Git and GitHub for the
useR][happy-git], which has much more detail than our abbreviated materials, and
is a good reference if you are confused or want to do something complicated.
She also gave [a talk on this topic][rstudioconf2017-jb] at rstudio::conf 2017.

## Other materials

### Reproducible (and generally good) coding practices

There are many materials on reproducible research, including the BES guide
mentioned above. For background, we recommend watching [this short
clip][ted-repro] by Matt Anticole for TED-Ed. **We require you to read** [this
article on sharing code][nature-repro] and [this guide on good coding
practices][dataist-coding]. None of this was written specifically for R
programmers, but there are useful tips for everyone (and some specific to R).

### R cheatsheets

RStudio and other contributors provide a variety of [cheatsheets][rstudio-cheat]
that summarise functionality of a variety of different topics in R, including
markdown in reports, on RStudio itself, and everything from Base R to package
development to parallel computing in R. **The main cheatsheets can be found
in RStudio under** <span style="color: #de77ae;">Help > Cheatsheets</span>.

### R Markdown

R Markdown allows you to generate reports from your R code or, as RStudio puts it,
to *"turn your analyses into high quality documents, reports, presentations and
dashboards."* As well as the cheatsheets and reference guide above, there are a
variety of resources for R Markdown:

- RStudio's [R Markdown website][rmd-rstudio], including:
  * [Pandoc's markdown website][rmd-pandoc], which describes the non-R parts of
    the format
- [R Markdown: The Definitive Guide][rmd-book] - an e-book by Yihui Xie, J. J.
  Allaire and Garrett Grolemund
  
These are great resources, and can help you to produce everything from the
simple reports you will be generating on this course, to the lectures slides 
and website we use to run this course, to complex interactive [Shiny
apps][shiny-rstudio]. Like Hadley Wickham's books, they are probably references
you will refer to later more than during the course, but they are completely
comprehensive if you want to look anything up.

Particularly useful for you here are the instructions in *Happy Git and GitHub
for the useR* for [changing R Markdown into R scripts][rmd-to-r] of the kind you
will be generating in these exercises.

### R Coder

The [Learn R section][rcoder-learnr] of this website provides explanations for a
lot of common techniques that you use during this course in the *Programming*
section. If you are confused by our explanations, you may find this useful.

### R coding style

Version 1 of Advanced R provides [a style guide][style-advanced-r]. In version
2, this has been replaced by the [tidyverse][tidyverse] [style
guide][style-tidyverse]. Google have [an adaptation of this][style-google].
We do not ask (or even recommend) that you follow any of them, but they are well
thought through, and you may decide you like one of them.

We only ask that your style is consistent, that you use meaningful names for
functions and variables, and that you **never** use dots (`.`) in function names
or use `rm(...)` or install any packages in the code you submit for assessment.

[hadley-wickham]: https://github.com/hadley
[tidyverse]: https://www.tidyverse.org
[tidyverse-packages]: https://www.tidyverse.org/packages
[style-tidyverse]: https://style.tidyverse.org
[ggplot2]: https://ggplot2.tidyverse.org
[dplyr]: https://dplyr.tidyverse.org
[R4DS]: https://r4ds.had.co.nz
[R4DS-solutions]: https://jrnold.github.io/r4ds-exercise-solutions
[advanced-r]: http://adv-r.had.co.nz
[advanced-r-solutions]: https://advanced-r-solutions-ed1.netlify.app
[style-advanced-r]: http://adv-r.had.co.nz/Style.html
[advanced-r2]: https://adv-r.hadley.nz
[advanced-r2-solutions]: http://advanced-r-solutions.rbind.io
[r-packages]: https://r-pkgs.org
[naturally-speaking]: https://naturallyspeaking.blog/2016/06/22/episode-41-conversations-with-an-r-jedi

[BES]: https://www.britishecologicalsociety.org
[BES-journals]: https://www.britishecologicalsociety.org/publications/journals
[BES-MEE]: https://www.britishecologicalsociety.org/publications/journals/methods-in-ecology-and-evolution
[BES-guides]: https://www.britishecologicalsociety.org/publications/guides-to
[BES-repro]: https://www.britishecologicalsociety.org/wp-content/uploads/2019/06/BES-Guide-Reproducible-Code-2019.pdf
[BES-data]: https://www.britishecologicalsociety.org/wp-content/uploads/2019/06/BES-Guide-Data-Management-2019.pdf

[jenny-bryan]: https://github.com/jennybc
[happy-git]: https://happygitwithr.com
[rmd-to-r]: https://happygitwithr.com/r-test-drive.html
[what-they-forgot]: https://rstats.wtf
[name-files]: https://speakerdeck.com/jennybc/how-to-name-files

[rstudioconf2020-jb]: https://rstudio.com/resources/rstudioconf-2020/object-of-type-closure-is-not-subsettable
[rstudioconf2017-jb]: https://rstudio.com/resources/rstudioconf-2017/happy-git-and-gihub-for-the-user-tutorial

[rstudio-cheat]: https://rstudio.com/resources/cheatsheets
[rmd-rstudio]: https://rmarkdown.rstudio.com
[rmd-book]: https://bookdown.org/yihui/rmarkdown
[rmd-pandoc]: https://rmarkdown.rstudio.com/authoring_pandoc_markdown.html
[shiny-rstudio]: https://shiny.rstudio.com

[nature-repro]: https://www.nature.com/articles/nn.4550
[dataist-coding]: https://thedataist.com/ten-good-coding-practices-for-data-scientists
[ted-repro]: https://ed.ted.com/lessons/is-there-a-reproducibility-crisis-in-science-matt-anticole

[rcoder-learnr]: https://r-coder.com/learn-r

[style-google]: https://google.github.io/styleguide/Rguide.html
