---
title: "Useful Resources"
date: '`r format(Sys.Date(), "%B %d %Y")`'
output:
  rmarkdown::html_vignette:
  toc: true
  toc_depth: 2
  vignette: >
    %\VignetteIndexEntry{Useful Resources}
    %\VignetteEngine{knitr::knitr}
    %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Reference materials

## British Ecological Society

The [British Ecological Society (BES)][BES] is the oldest ecological society in
the world, and one of the largest. It publishes [several excellent
journals][BES-journals], including [Methods in Ecology and Evolution][BES-MEE],
which publishes many software packages.

The society also provides many several [guides on better science][BES-guides].
As part of the course, **we require you to read the following guides**:

- [Reproducible Code][BES-repro]
- [Data Management][BES-data]

## Hadley Wickham

[Hadley Wickham][hadley-wickham] is the Chief Scientist for RStudio. He created
the original `ggplot` library for his PhD. These days his
[data analysis packages][tidyverse-packages] are collectively known as the
[tidyverse][tidyverse], the most famous of which are probably [ggplot2][ggplot2]
and [dplyr][dplyr]. He has written three very useful books on data analysis and
software development in R:

- [R for Data Science (R4DS)][R4DS]
  * [Solutions to the exercises][R4DS-solutions]
- Advanced R
  - [1st edition][advanced-r] (I find this easier to navigate)
    * [Solutions to the exercises][advanced-r-solutions]
  - [2nd edition][advanced-r2] (this is obviously updated)
    * [Solutions to the exercises][advanced-r2-solutions]
- [R Packages][r-packages]

We recommend all of these books as reference material, and will point to
specific chapters at different times, but the books themselves are probably too
long for you to read in their entirety. Nonetheless keep them for future
reference, as they contain an enormous amount of knowledge about R in a
(relatively!) compact form.

## Assorted other materials

### Understanding, avoiding and fixing errors in your code

As part of the course, **we require you to watch [this
keynote][rstudioconf2020-jb]** from rstudio::conf 2020 by [Jenny
Bryan][jenny-bryan] of RStudio. It is an excellent keynote on errors in R and
how to identify and fix them.

### Git and GitHub in R and RStudio

Git is a very complex tool -- it is used to manage the development of the whole
Linux kernel! -- so we cover only the most basic aspects of it. As well as the
above, Jenny (with others) has written an excellent resource for using git and
GitHub in R -- [Happy Git and GitHub for the useR][happy-git], which has much
more detail than our abbreviated materials, and is a good reference if you are
confused or want to do something complicated. She also gave [a talk on this
topic][rstudioconf2017-jb] at rstudio::conf 2017.

### Reproducible (and generally good) coding practices

There are many materials on reproducible research, including the BES guide
mentioned above. For background, we recommend watching [this short
clip][ted-repro] by Matt Anticole for TED-Ed. **We require you to read** [this
article on sharing code][nature-repro] and [this guide on good coding
practices][dataist-coding]. None of this was written specifically for R
programmers, but there are useful tips for everyone (and some specific to R).

### R cheatsheets

RStudio and other contributors provide a variety of [cheatsheets][rstudio-cheat]
that summarise functionality of a variety of different topics in R, including
markdown in reports, on RStudio itself, and everything from Base R to package
development to parallel computing in R. **The main cheatsheets are available
directly from RStudio under *Help -> Cheatsheets*.**

### R Markdown

R Markdown allows you to produce reports from your R code or, as RStudio put it,
to *"turn your analyses into high quality documents, reports, presentations and
dashboards."* As well as the cheatsheet and reference guide above, there are a
variety of resources for R Markdown:

- RStudio's [R Markdown website][rmd-rstudio], including:
  * [Pandoc's markdown website][rmd-pandoc], which describes the non-R parts of
    the format
- [R Markdown: The Definitive Guide][rmd-book] - an e-book by Yihui Xie, J. J.
  Allaire and Garrett Grolemund
  
These are great resources, and can help you to produce everything from the
simple reports you will be generating on this course, the lectures we are giving
and this website with the course documentation, to complex interactive [Shiny
apps][shiny-rstudio]. Like Hadley Wickham's books, they are probably references
you will refer to later more than during the course, but they are completely
comprehensive if you want to look anything up.

Particularly useful for you here are the instructions in *Happy Git and GitHub
for the useR* for [changing R Markdown into R scripts][rmd-to-r] of the kind you
will be generating in these exercises.

### R Coder

The [Learn R section][rcoder-learnr] of this website provides explanations for a
lot of common techniques that you use during this course in the *Programming*
section. If you are confused by our expalanations, you may find this useful.

### R coding style

Version 1 of Advanced R provides [a style guide][style-advanced-r]. In version
2, this has been replaced by the [tidyverse][tidyverse] [style
guide][style-tidyverse]. Google have [an adaptation of this][style-google].
We do not ask (or even recommend) that you follow any of them, but they are well
thought through, and you may decide you like one of them.

We only ask that your style is consistent, that you use meaningful names for
functions and variables, and that you **never** use dots (`.`) in function names
or use `rm(...)` or install any packages in the code you submit for assessment.

# Specific techniques

## Loops

Loops allow you to repeat the same thing again and again. If you are doing
something more than two or three times, you should try to find a loop to use
that will avoid you having to copy and paste the same code over and over again,
with the associated risks not only of mistyping or not copying correctly, but
also of confusing by filling your R scripts with nearly identical chunks of
code. There are fundamentally two kinds of loop:

- one where you know exactly how many times the loop will run, for instance
  because you are carrying something out once for each element of a vector or
  row or column of a data frame; and
- one where you do not, because some part of your calculation in each step of
  the loop will determine whether to continue or to stop.

### `for (...)` loops

`for` loops allow us to repeat something *for* a fixed number of times (*e.g.*
once per element of a vector, once per row of a data frame, *etc.*). 


They are
called as:

```{R}
greetings <- c("Hello", "Goodbye")
for (word in greetings) {
  # body
}
```

and in each run through the loop, the variable, here `word`, is updated with
the next element (here, in the vector `greetings`). We introduced them in week 1
and again in [Lecture 5b][lecture-5b] on Wednesday 27th and Practical
`practicalA-1`. They were then used starting in Practical `practical1-1`.

There is a section in R4DS (within a more general chapter on
[*Iteration*][R4DS-iteration]) that covers [`for` loops][for-R4DS]. For loops
are also covered by R Coder [here][for-rcoder].

### `while (...)` loops

`while` loops allows us to repeat something *while* a condition is still `TRUE`.
They are particularly useful when you don't know in advance exactly how many
times something will be done, but can be used in any situation. Unlike `for`
loops you need to update everything manually each time around:


```{R, eval=FALSE}
test <- some_test()
while (test) {
  # Do something
  test <- update(something)
}
```

`test` is checked each time around, and as long as `test` continues to be
`TRUE`, the code block inside the curly brackets `{ ... }` is run. Be careful
that if you don't update `test` inside that block, then it will continue for
ever! However, if (when!) `test` is finally `FALSE`, the loop ends and R
continue to the next piece of code.

We introduced them on Wednesday 27th in [Lecture 5b][lecture-5b]
and in `practicalA-2`, and used them from Practical `practical2-4`. There is a
section in R4DS (within a more general chapter on [*Iteration*][R4DS-iteration])
that covers [`while` loops][while-R4DS]. While loops are also covered by R Coder
[here][while-rcoder].

## Flow control

### Comparisons -- testing for equality and difference

These tests are essential for `while` loops, and other forms of flow control
such as `if` statements. They allow us to test whether something is true, and
change what lines of code are run depending on the outcome. There are the
basic tests:

- `a == b`: is `a` equal to `b`? (`TRUE` if this is true, `FALSE` if this is false)
- `a > b`: is `a` greater than `b`?
- `a < b`: is `a` less than `b`?
- `a >= b`: is `a` greater than or equal to `b`?
- `a <= b`: is `a` less than or equal to `b`?
- `a != b`: is `a` different from `b`?

There are then three basic ways of changing or combining the above:

- `(a < b) || (c == d)`: is **either ** `a` less than `b` **or** `c` equal to `d`?
- `(a < b) && (c == d)`: is **both** `a` less than `b` **and** `c` equal to `d`?
- `!((a < b) && (c == d))`: is the above **not** `TRUE`? `TRUE` if the above was
  `FALSE` and vice versa 

Remember to use lots of brackets to ensure you are combining things in the right
order. These tests are used in `while` loops above to determine whether to
continue through the loop again, and in `if` statements below, to determine what
to do next.

We introduced these concepts on Friday 29th, and again in [Lecture
7a][lecture-7a] on Monday 1st and Practical `practicalA-2`. Comparisons are also
covered [in passing][operators-R4DS] in R4DS, and by R Coder in a bit more
depth [here][operators-rcoder].

### `if (something)` and `if (something) { ... } else { ... }` statements

The `if` command allow us to carry out a test, and if the result is `TRUE` carry
out a block of R code (in curly brackets `{ ... }`). Optionally, if it is
`FALSE`, a different block of code can be run instead. This allows us to do a
variety of things. To give a very simple example:

```{R}
if (2 > 1) {
  print("Maths works!")
}
```

This prints `[1] "Maths works!"` because the test is `TRUE`, so the code block
that follows is run. Whereas:

```{R}
if (2 >= 5) {
  print("At least 5.")
} else {
  print("Less than or equal to 5.")
}
```

This prints `[1] "Less than or equal to 5."` because the test was false, so R
continues to the code block after the `else` statement. If there is no `else`
statement, then no code is run, so:

```{R}
if (2 >= 5) {
  print("At least 5.")
}
```

does nothing. We use 'if` and `if ... else` statements throughout the helper
functions provided to you, and also in a couple of ways in the example code we
provide you. For instance:

```{R}
library(codetools)
library(RPiR)

if (length(findGlobals(plot_simple, merge=FALSE)$variables) != 0)
{
  stop("Function plot_simple() may not use global variable(s): ",
       findGlobals(plot_simple, merge=FALSE)$variables)
}
```

This checks whether `length(findGlobals(plot_simple, merge=FALSE)$variables)` is
non-zero, which is to say whether the `variables` element of what is returned by
`findGlobals(plot_simple, merge=FALSE)` is not of length zero, *i.e.* whether
there are any global variables in the function `plot_simple`. If there are, then
the contents of the curly brackets are run, `stop(...)` is called, and the code
stops running. In fact, `plot_simple` has no global variables, so the code block
is not run.

The second example we provide of using an `if` statement to control code
execution is in Practical `practical3-4`:

```{R, eval = FALSE}
if (first.graph) {
  plot_populations(final.populations,
                   new.graph = TRUE, 
                   col = c(susceptibles = "green", infecteds = "red"))
  first.graph <- FALSE 
} else {
  plot_populations(final.populations,
                   new.graph = FALSE,
                   col = c(susceptibles = "green", infecteds = "red"))
}
```

This code tests whether the variable `first.graph` is `TRUE`. If it is, the
following code block is run, and it plots a graph into a new graphics window and
sets `first.graph` to `FALSE`. This code is run inside a loop (see above), and
the next (and every subsequent) time it runs, `first.graph` is already `FALSE`
so the code block following the `else` statement is run, and a plot is
superimposed on the existing graphics window.

R Coder covers the basics of `if` statements [here][if-rcoder]. R4DS seems to
consider them too simple, but ironically they have [a chapter in Advanced
R][if-advanced-r2]; however, this contains a lot of advanced topics in flow
control that are well beyond the scope of this course.

## Functions

Just as loops allow you to repeat the same code chunk again and again in one
place, functions allow you to repeat the same task multiple times, but
potentially in multiple places on different data. If you have a complex piece
of code that does a single discrete thing, then you may want to wrap it up
into a function so that you can refer to it by a simple name and keep the
script that calls it clear and easy to read.

To quote from [the introduction to R4DS on functions][functions-R4DS]:

> One of the best ways to improve your reach as a data scientist is to write functions. Functions allow you to automate common tasks in a more powerful and general way than copy-and-pasting. Writing a function has three big advantages over using copy-and-paste:
>
> 1. You can give a function an evocative name that makes your code easier to understand.
>
> 2. As requirements change, you only need to update code in one place, instead of many.
>
> 3. You eliminate the chance of making incidental mistakes when you copy and paste (i.e. updating a variable name in one place, but not in another).

Functions allow us to wrap up a common task into a single line of code,
irrespective of how complex and long the code chunk is, and to describe it
with words of your choosing irrespective of how inscrutable the R is that is
being run. Functions also leave you with only a single place that needs to be
checked for correctness, rather than all of the places that you have pasted
copies of your original chunk of code into.

Functions are really easy to write:

```{R}
add_up <- function(first, second) {
  first + second
}

# Add call the function to add 3 to 5!
add_up(3, 5)
```

The critical thing to know is that your code should take its just arguments,
here the variables `first` and `second`, and do some things to them to calculate
some result. That result is just whatever the last line of code is that is run.
If you are writing a simple function, this will be the final line before the
close curly bracket (`}`), here `squared`.

```{R}
add_and_square <- function(first, second) {
  # Calculate the result
  added <- first + second
  squared <- added * added
  # And return it
  squared
}

# And call the function to add 3 to 5 and square it!
add_and_square(3, 5)
```

We introduced functions in [Lecture 2c][lecture-2c] on Wednesday 20th and
Practical `practicalA-1`and then again in [Lecture 5b][lecture-5b] on Wednesday
27th. They were used starting in Practical `practical1-2`.

Functions are covered in R4DS [here][functions-R4DS], and R Coder covers
them in some depth [here][functions-rcoder]. Advanced R covers functions in
enormous detail starting [here][functions-advanced-r] with an introduction to
functional programming, and continuing for several chapters.

[lecture-2c]: https://ibahcm.github.io/RPiR/lectures_html/RPiR2c-development.html
[lecture-5b]: https://ibahcm.github.io/RPiR/lectures_html/RPiR5b-R.html
[lecture-7a]: https://ibahcm.github.io/RPiR/lectures_html/RPiR7a-R.html

[hadley-wickham]: https://rstudio.com/speakers/hadley-wickham
[tidyverse]: https://www.tidyverse.org
[tidyverse-packages]: https://www.tidyverse.org/packages
[style-tidyverse]: https://style.tidyverse.org
[ggplot2]: https://ggplot2.tidyverse.org
[dplyr]: https://dplyr.tidyverse.org
[R4DS]: https://r4ds.had.co.nz
[R4DS-iteration]: https://r4ds.had.co.nz/iteration.html
[for-R4DS]: https://r4ds.had.co.nz/iteration.html#for-loops
[while-R4DS]: https://r4ds.had.co.nz/iteration.html#unknown-sequence-length
[operators-R4DS]: https://r4ds.had.co.nz/transform.html?q=compa#comparisons
[functions-R4DS]: https://r4ds.had.co.nz/functions.html
[R4DS-solutions]: https://jrnold.github.io/r4ds-exercise-solutions
[advanced-r]: http://adv-r.had.co.nz
[advanced-r-solutions]: https://advanced-r-solutions-ed1.netlify.app
[style-advanced-r]: http://adv-r.had.co.nz/Style.html
[advanced-r2]: https://adv-r.hadley.nz
[advanced-r2-solutions]: http://advanced-r-solutions.rbind.io
[if-advanced-r2]: https://adv-r.hadley.nz/control-flow.html
[functions-advanced-r2]: https://adv-r.hadley.nz/fp.html
[r-packages]: https://r-pkgs.org

[BES]: https://www.britishecologicalsociety.org
[BES-journals]: https://www.britishecologicalsociety.org/publications/journals
[BES-MEE]: https://www.britishecologicalsociety.org/publications/journals/methods-in-ecology-and-evolution
[BES-guides]: https://www.britishecologicalsociety.org/publications/guides-to
[BES-repro]: https://www.britishecologicalsociety.org/wp-content/uploads/2019/06/BES-Guide-Reproducible-Code-2019.pdf
[BES-data]: https://www.britishecologicalsociety.org/wp-content/uploads/2019/06/BES-Guide-Data-Management-2019.pdf

[jenny-bryan]: https://rstudio.com/speakers/jenny-bryan
[happy-git]: https://happygitwithr.com
[rmd-to-r]: https://happygitwithr.com/r-test-drive.html

[rstudioconf2020-jb]: https://rstudio.com/resources/rstudioconf-2020/object-of-type-closure-is-not-subsettable
[rstudioconf2017-jb]: https://rstudio.com/resources/rstudioconf-2017/happy-git-and-gihub-for-the-user-tutorial

[rstudio-cheat]: https://rstudio.com/resources/cheatsheets
[rmd-rstudio]: https://rmarkdown.rstudio.com
[rmd-book]: https://bookdown.org/yihui/rmarkdown
[rmd-pandoc]: https://rmarkdown.rstudio.com/authoring_pandoc_markdown.html
[shiny-rstudio]: https://shiny.rstudio.com

[nature-repro]: https://www.nature.com/articles/nn.4550
[dataist-coding]: https://thedataist.com/ten-good-coding-practices-for-data-scientists
[ted-repro]: https://ed.ted.com/lessons/is-there-a-reproducibility-crisis-in-science-matt-anticole

[rcoder-learnr]: https://r-coder.com/learn-r
[for-rcoder]: https://r-coder.com/for-loop-r
[while-rcoder]: https://r-coder.com/while-loop-r
[operators-rcoder]: https://r-coder.com/operators-r
[if-rcoder]: https://r-coder.com/if-else-r
[functions-rcoder]: https://r-coder.com/function-r

[style-google]: https://google.github.io/styleguide/Rguide.html
