---
title: "Introduction"
output: 
  ioslides_presentation: default
  html_document: default
---

## (Reproducible) Programming in R

Lecturers:

- Richard Reeve
- Sonia Mitchell

Demonstrators:

- Yacob Haddou
- Jamie Burton

# Communication

## 1. Zoom

Please do ask question live in the Zoom classes:

 - Mondays 1-5pm, Wednesdays 1-5pm and Fridays 1-4pm until 15th Feb

## 2. Moodle

The course is officially on Moodle at https://moodle.gla.ac.uk/course/view.php?id=23343 -
let me know if you can't access it. All submissions will be through Moodle,
and lecture recordings and some downloads will be available there. However...

## 3. GitHub

Once you have GitHub set up we will use it for most of our queries, and the
course is available at https://github.com/IBAHCM/RPiR. Please ask for help and
discuss issues on the Discussions tab at https://github.com/IBAHCM/RPiR/discussions.

## 4. Email

Feel free to email myself at richard.reeve@glasgow.ac.uk and Sonia at
sonia.mitchell@glasgow.ac.uk if you want to contact us directly.

# Plan for today

## Get everything installed

All of the course preparation instructions are in the course's documentation at
https://ibahcm.github.io/RPiR under **Course preparation**. The same page is
also duplicated on the package's GitHub page at https://github.com/IBAHCM/RPiR:

- First follow the instructions there to make sure you have an up-to-date version
of R and RStudio.
- Then follow the links following on from there to pages that tell you how to
install the course itself and create the necessary accounts.

## Read the other materials

Moodle has some links to other materials to read or watch when you finish
installing everything.

# Any Questions?
