---
title: "2-5: SIR model"
output: 
  learnr::tutorial:
    theme: lumen
    includes:
      in_header: !expr system.file("tutorials/google-font.html", package = "RPiR")
  html_document: default
runtime: shiny_prerendered
description: >
  Students adapt their code to write an SIR model.
---

```{r setup, include=FALSE}
library(learnr)

knitr::opts_chunk$set(error = TRUE)
set.seed(123)
```

## Overview

*In this practical we will take our SIS model and extend it to produce the Susceptible-Infected-Recovered or SIR model. In this instance we’ll use the parameters for foot-and- mouth disease, a highly infectious disease of ruminants – in this case cattle.*

## Background

The SIR model in difference equation form is given by the following equations:

$$S(t+1) = S(t) – \beta\; \frac{S(t)\; I(t)}{N}$$
$$I(t+1) = I(t) + \beta\; \frac{S(t)\; I(t)}{N} – \sigma\; I(t)$$
$$R(t+1) = R(t) + \sigma\; I(t)$$

## Tasks

Your task is to edit the files from the previous practical 
(<span style="color: #de77ae;">0203-deterministic-SIS.r</span> and 
<span style="color: #de77ae;">0203-run-SIS.r</span>) to produce
the corresponding files 
<span style="color: #de77ae;">0204-deterministic-SIR.r</span> and 
<span style="color: #de77ae;">0204-run-SIR.r</span> that 
run the SIR model rather than the SIS model. There shouldn’t be too many changes 
that are necessary, though obviously the first is to add a new population (the
**recovereds**) to the data frame and remember than $N$, the total population size, 
now includes the recovereds too. Also remember that if you change the name of 
the function, for example from `timestep_deterministic_SIS()` to
`timestep_deterministic_SIR()` you need to change it in both files. 

Because
foot-and-mouth disease (FMD) is so transmissible that the disease flashes 
through a herd very quickly, to model it we normally deal with farms rather than
individual animals when we are thinking about transmission and recovery, so an
"individual" is actually a farm in the model. This makes no difference to your 
code, but may change your choice of some variable names. You’ll therefore need 
to know the transmission and recovery rates of farms, and very roughly, running 
in timesteps of weeks again, we can use a transmission rate of 2 and a recovery
rate of 1/2. Note that with such high transmission and recovery rates, you’ll 
find the outbreak finishes very quickly, so you should find that the end time of
the simulation can be quite short, and you should find that the timestep will 
have to be below 1 to be stable.

## Running the code

Run the code by running your new file <span style="color: #de77ae;">0204-run-SIR.r</span>. Check that you get the 
same results as you saw in the lecture for an $R_0$ of 2. Adding the argument
`col=c("green", "red", "black")` to `plot_populations()` will allow you to 
change the colours of the plot to match those from the lecture.

## Report

Create a report showing farm-to-farm transmission of FMD, displaying the output
of its SIR model in a figure. You could for instance show how that differs 
from an SIS model with the same $R_0$, or another SIR model with a different
$R_0$.
